### ISSUE TITLE
Cote d'Ivoire 10 abstract proposal clarification

### ISSUE THREAD

**Issue by glenntav** [glenntav/gc#38]

**Comment by glenntav** [comment]
7 Sept 23 - no response received

**Comment by glenntav** [comment]
8 Sept 23
- email from the participant indicating that no feedback had been received to their presentation proposal.
- investigation reveals that their email address at their affiliated institution (Institut National de la Statistique – Côte d’Ivoire) e********u@plan.gouv.ci has been used recorded and used for the request for clarification, but they are instead using a @hotmail.com address for communication.

9 Sept 23
- Responded to both the hotmail and institutional email addresses copying in the OC's 28 Aug 23 request for clarification.

**Comment by ChallenerSJ** [comment]
Hi @glenntav, as it stands the Agenda WG has agreed to reject this proposal. This ticket can be closed. Although if a reply and updated abstract is provided we would gladly review it considering the low number of submissions from the African region.
